/******** DO NOT EDIT THIS FILE ********/
#include <stdio.h>
#include <string.h>
#include "test_shobject_name.h"
#include "../shobject_name.h"

int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

static void assert_shobject_name(char* actual_label, char* expected_label) {
    char actual_name[MAX_SHOBJ_NAME_SIZE];
    char expected_name[MAX_SHOBJ_NAME_SIZE];
    
    char* user = getenv("USER");
 
    if (!user) user = "anon";
    
    if (!actual_label || !actual_label[0])
        expected_label = "none";
               
    if (!expected_label)
        expected_label = actual_label;

    snprintf(expected_name, MAX_SHOBJ_NAME_SIZE, SHOBJ_NAME_FORMAT, 
        user, expected_label);   

    shobject_name(actual_name, actual_label);    
    
    assert_string_equal(actual_name, expected_name);
    
    assert_int(strnlen(actual_name, MAX_SHOBJ_NAME_SIZE), < ,    
        MAX_SHOBJ_NAME_SIZE);
}


static MunitResult test_shobject_name(const MunitParameter params[], 
    void* fixture) {      
    assert_shobject_name("test", NULL);
      
    assert_shobject_name("", NULL);

    assert_shobject_name(NULL, NULL);
    
    assert_shobject_name("a", NULL);

    char* user = getenv("USER");

    int user_len = strnlen(user, 9);
    int chars_left = MAX_SHOBJ_NAME_SIZE - 1 - user_len - 10;
    
    char expected_label[chars_left + 1];
    
    int i;
    for (i = 0; i < chars_left + 1; i++)
        expected_label[i] = 'x';
    
    expected_label[i] = '\0';
    
    assert_shobject_name("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 
        expected_label);  
        
    return MUNIT_OK;
}   
